### ISSUE TITLE
The template live reloading can't work

### ISSUE THREAD

**Issue by rzhb** [LionelWoody/spring-boot-starter-pebble#1]
I think with `spring.pebble.cache=false` in file`application.properties`, when the templates changed all I need to do is refresh the web browser to see the changes. But this not work like what I thought.

**Comment by LionelWoody** [comment]
Sorry for late.
I'm glad to know I have a user:)
bug fixed. try it now.

**Comment by rzhb** [comment]
It works fine now. Thank you.
