### ISSUE TITLE
Problems when extending other templates

### ISSUE THREAD

**Issue by Arcnor** [LionelWoody/spring-boot-starter-pebble#2]
Using the example from the Pebble website, I have 2 files, `src/main/resources/templates/base.html` and `src/main/resources/templates/home.html`.

When doing `{% extends "base.html" %}`, Pebble will throw an error saying it can't find `base.html`.

If you change it to `{% extends "templates/base.html" %}`, everything works, so I'm guessing the template locator provided to Pebble doesn't provide the correct routes for relative paths to work.

**Comment by LionelWoody** [comment]
the starter will add prefix & suffix to the template, so the extends would be `{% extends "base" %}`, a little difference from Pebble website.

**Comment by Arcnor** [comment]
You are completely right, it works like that. Maybe this should be added to the `README` or similar?

Anyway, this can be closed now :)
