### ISSUE TITLE
Session supported?

### ISSUE THREAD

**Issue by robertotru** [LionelWoody/spring-boot-starter-pebble#4]
Hi,

Am I wrong or currently there is no support for the `HttpSession` in a template?

**Comment by LionelWoody** [comment]
Template engine know nothing about HttpSession or HttpRequest, you must put it to the Model manually.
I tested the velocity template, same as pebble.
test code in https://github.com/LionelWoody/miniDemo
branch master & branch velocity.

**Comment by robertotru** [comment]
Yeah, got it. In theory it is possible to define a standard controller advice that flushes the session into a standard model object, using a library like JavaAssist to create the session mapping object at runtime, so that we have all the getters, something like:

```
@ControllerAdvice
public class ShoppingBagSessionBuilder {

    @Autowired(required = true)
    private HttpServletRequest request;

    public Object setShoppingBagTotalPrice() throws Throwable {
        final HttpSession session = request.getSession(true);
        Enumeration<String> enumeration = session.getAttributeNames();
        Object sessionMapping = //Use JavaAssist to create the object at runtime
        while(enumeration.hasMoreElements()){
            //Mapping each value to a new field in sessionMapping
        }        

        return sessionMapping;
    }

}
```

So this could be an additional feature that can be enabled using the application.properties.
Thanks for your feedback
